// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_try.Data;

#nullable disable

namespace Project_try.Migrations
{
    [DbContext(typeof(MVCDemoDbContext))]
    [Migration("20230421174841_Users")]
    partial class Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_try.Models.Penduduk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kabupaten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_penduduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nik")
                        .HasColumnType("int");

                    b.Property<DateTime>("tanggal_lahir")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Penduduk");
                });

            modelBuilder.Entity("Project_try.Models.ReportInnVaksin", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date_In_Vaksin")
                        .HasColumnType("datetime2");

                    b.Property<string>("id_vaksin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("jumlah_vaksin")
                        .HasColumnType("int");

                    b.Property<string>("name_rumah_sakit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Project_try.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama_Badan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project_try.Models.Vaksin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVaksin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description_vaksin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("min_age_used")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vaksins");
                });
#pragma warning restore 612, 618
        }
    }
}
