// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_try.Data;

#nullable disable

namespace Project_try.Migrations
{
    [DbContext(typeof(MVCDemoDbContext))]
    [Migration("20230411080159_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_try.Models.Vaksin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVaksin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description_vaksin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("min_age_used")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vaksins");
                });
#pragma warning restore 612, 618
        }
    }
}
