//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Tracking_Vaksin_Proyek_try
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penduduk
    {
        public int Id { get; set; }
        public string nik { get; set; }
        public string Provinsi { get; set; }
        public string Kabupaten { get; set; }
        public string Kecamatan { get; set; }
        public string name_penduduk { get; set; }
        public System.DateTime tanggal_lahir { get; set; }
    }
}
