//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Tracking_Vaksin_Proyek_try
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportInnVaksin
    {
        public System.Guid id { get; set; }
        public string name_rumah_sakit { get; set; }
        public int jumlah_vaksin { get; set; }
        public System.DateTime Date_In_Vaksin { get; set; }
        public string nama_vaksin { get; set; }
        public string id_rumah_sakit { get; set; }
        public string id_vaksin { get; set; }
    }
}
