//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Tracking_Vaksin_Proyek_try
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaksin
    {
        public System.Guid Id { get; set; }
        public string NameVaksin { get; set; }
        public string Dosis { get; set; }
        public int min_age_used { get; set; }
        public string description_vaksin { get; set; }
    }
}
